services:
  - type: web  # Definir tipo de servicio web
    name: APIRENIEC  # Nombre del servicio
    env: docker  # Especifica que está usando un entorno Docker
    plan: free  # Puedes cambiar esto según el plan que uses en Render
    dockerfilePath: ./Dockerfile  # Ruta a tu Dockerfile
    envVars:  # Definir variables de entorno
      - key: JAVA_HOME
        value: /usr/lib/jvm/java-17-openjdk-amd64
      - key: SPARK_VERSION
        value: 3.5.1
      - key: HADOOP_VERSION
        value: 3.3.6
      - key: SPARK_HOME
        value: /opt/spark
      - key: HADOOP_HOME
        value: /opt/hadoop
      - key: PATH
        value: $PATH:$JAVA_HOME/bin:$SPARK_HOME/bin:$HADOOP_HOME/bin
    healthCheckPath: /  # Ruta para la verificación del estado de la aplicación
    autoDeploy: true  # Implementa automáticamente tras cada confirmación en el repositorio
