# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'new_correctivo2_edit.ui'
##
## Created by: Qt User Interface Compiler version 5.15.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide2.QtCore import *
from PySide2.QtGui import *
from PySide2.QtWidgets import *


class Ui_NewBook(object):
    def setupUi(self, NewBook):
        if not NewBook.objectName():
            NewBook.setObjectName(u"NewBook")
        NewBook.resize(1011, 584)
        NewBook.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: grey;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:grey;\n"
"	color:white;\n"
"}")
        self.label = QLabel(NewBook)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(20, 10, 981, 41))
        font = QFont()
        font.setUnderline(False)
        self.label.setFont(font)
        self.label.setFocusPolicy(Qt.ClickFocus)
        self.label.setAutoFillBackground(False)
        self.label.setStyleSheet(u"background-color: blue;")
        self.label.setFrameShape(QFrame.Box)
        self.label_autoriza = QLabel(NewBook)
        self.label_autoriza.setObjectName(u"label_autoriza")
        self.label_autoriza.setGeometry(QRect(20, 70, 101, 21))
        self.inputCodigo = QLineEdit(NewBook)
        self.inputCodigo.setObjectName(u"inputCodigo")
        self.inputCodigo.setGeometry(QRect(20, 90, 111, 31))
        font1 = QFont()
        font1.setPointSize(12)
        self.inputCodigo.setFont(font1)
        self.inputInmueble = QLineEdit(NewBook)
        self.inputInmueble.setObjectName(u"inputInmueble")
        self.inputInmueble.setGeometry(QRect(140, 90, 221, 31))
        self.inputInmueble.setFont(font1)
        self.addButton = QPushButton(NewBook)
        self.addButton.setObjectName(u"addButton")
        self.addButton.setGeometry(QRect(200, 530, 291, 41))
        font2 = QFont()
        font2.setPointSize(14)
        font2.setBold(True)
        font2.setWeight(75)
        self.addButton.setFont(font2)
        self.addButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.addButton.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: #0069c0;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:#0069c0;\n"
"	color:white;\n"
"}")
        icon = QIcon()
        icon.addFile(u"./assets/icons/save-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.addButton.setIcon(icon)
        self.addButton.setIconSize(QSize(30, 30))
        self.addButton.setAutoDefault(True)
        self.addButton.setFlat(True)
        self.cancelButton = QPushButton(NewBook)
        self.cancelButton.setObjectName(u"cancelButton")
        self.cancelButton.setGeometry(QRect(530, 530, 271, 41))
        self.cancelButton.setFont(font2)
        self.cancelButton.setCursor(QCursor(Qt.PointingHandCursor))
        self.cancelButton.setStyleSheet(u"QPushButton\n"
"{	\n"
"	height: 2em;\n"
" 	border-style: solid;\n"
"	border-width: 2px;\n"
" 	border-color: grey;\n"
"	font-weight: bold;\n"
"}\n"
"\n"
"QPushButton:hover\n"
"{\n"
"   	background-color:grey;\n"
"	color:white;\n"
"}")
        icon1 = QIcon()
        icon1.addFile(u"./assets/icons/cancel-icon.png", QSize(), QIcon.Normal, QIcon.Off)
        self.cancelButton.setIcon(icon1)
        self.cancelButton.setIconSize(QSize(30, 30))
        self.cancelButton.setAutoDefault(True)
        self.cancelButton.setFlat(True)
        self.label_aquienVisita = QLabel(NewBook)
        self.label_aquienVisita.setObjectName(u"label_aquienVisita")
        self.label_aquienVisita.setGeometry(QRect(140, 70, 191, 21))
        self.label_area = QLabel(NewBook)
        self.label_area.setObjectName(u"label_area")
        self.label_area.setGeometry(QRect(500, 70, 191, 21))
        self.inputDias = QLineEdit(NewBook)
        self.inputDias.setObjectName(u"inputDias")
        self.inputDias.setEnabled(False)
        self.inputDias.setGeometry(QRect(320, 160, 71, 31))
        self.inputDias.setFont(font1)
        self.label_fecha = QLabel(NewBook)
        self.label_fecha.setObjectName(u"label_fecha")
        self.label_fecha.setGeometry(QRect(20, 140, 111, 16))
        self.label_visitante = QLabel(NewBook)
        self.label_visitante.setObjectName(u"label_visitante")
        self.label_visitante.setGeometry(QRect(320, 140, 141, 21))
        self.inputMonto = QLineEdit(NewBook)
        self.inputMonto.setObjectName(u"inputMonto")
        self.inputMonto.setEnabled(False)
        self.inputMonto.setGeometry(QRect(410, 160, 151, 31))
        self.inputMonto.setFont(font1)
        self.label_entidad = QLabel(NewBook)
        self.label_entidad.setObjectName(u"label_entidad")
        self.label_entidad.setGeometry(QRect(410, 140, 151, 21))
        self.label_dni = QLabel(NewBook)
        self.label_dni.setObjectName(u"label_dni")
        self.label_dni.setGeometry(QRect(170, 140, 91, 21))
        self.label_nota_obligatoria = QLabel(NewBook)
        self.label_nota_obligatoria.setObjectName(u"label_nota_obligatoria")
        self.label_nota_obligatoria.setGeometry(QRect(20, 510, 281, 21))
        self.ast_aquienvisita = QLabel(NewBook)
        self.ast_aquienvisita.setObjectName(u"ast_aquienvisita")
        self.ast_aquienvisita.setGeometry(QRect(220, 70, 21, 21))
        self.ast_dni = QLabel(NewBook)
        self.ast_dni.setObjectName(u"ast_dni")
        self.ast_dni.setGeometry(QRect(250, 140, 21, 21))
        self.ast_fecha = QLabel(NewBook)
        self.ast_fecha.setObjectName(u"ast_fecha")
        self.ast_fecha.setGeometry(QRect(120, 140, 21, 21))
        self.label_area_2 = QLabel(NewBook)
        self.label_area_2.setObjectName(u"label_area_2")
        self.label_area_2.setGeometry(QRect(370, 70, 61, 21))
        self.label_area_3 = QLabel(NewBook)
        self.label_area_3.setObjectName(u"label_area_3")
        self.label_area_3.setGeometry(QRect(710, 70, 91, 21))
        self.inputFechaFin = QDateEdit(NewBook)
        self.inputFechaFin.setObjectName(u"inputFechaFin")
        self.inputFechaFin.setGeometry(QRect(170, 160, 131, 31))
        font3 = QFont()
        font3.setPointSize(11)
        font3.setBold(False)
        font3.setWeight(50)
        self.inputFechaFin.setFont(font3)
        self.inputFechaFin.setDateTime(QDateTime(QDate(2024, 12, 31), QTime(0, 0, 0)))
        self.inputDepartamento = QLineEdit(NewBook)
        self.inputDepartamento.setObjectName(u"inputDepartamento")
        self.inputDepartamento.setEnabled(False)
        self.inputDepartamento.setGeometry(QRect(500, 90, 201, 31))
        self.inputDepartamento.setFont(font1)
        self.inputTipo = QLineEdit(NewBook)
        self.inputTipo.setObjectName(u"inputTipo")
        self.inputTipo.setEnabled(False)
        self.inputTipo.setGeometry(QRect(370, 90, 121, 31))
        self.inputTipo.setFont(font1)
        self.inputDireccion = QLineEdit(NewBook)
        self.inputDireccion.setObjectName(u"inputDireccion")
        self.inputDireccion.setEnabled(False)
        self.inputDireccion.setGeometry(QRect(710, 90, 291, 31))
        self.inputDireccion.setFont(font1)
        self.inputFechaInicio = QDateEdit(NewBook)
        self.inputFechaInicio.setObjectName(u"inputFechaInicio")
        self.inputFechaInicio.setGeometry(QRect(20, 160, 131, 31))
        self.inputFechaInicio.setFont(font3)
        self.inputFechaInicio.setDateTime(QDateTime(QDate(2023, 11, 1), QTime(0, 0, 0)))
        self.plainTextObservaciones = QPlainTextEdit(NewBook)
        self.plainTextObservaciones.setObjectName(u"plainTextObservaciones")
        self.plainTextObservaciones.setGeometry(QRect(20, 420, 981, 91))
        self.label_fecha_2 = QLabel(NewBook)
        self.label_fecha_2.setObjectName(u"label_fecha_2")
        self.label_fecha_2.setGeometry(QRect(20, 400, 161, 16))
        self.line = QFrame(NewBook)
        self.line.setObjectName(u"line")
        self.line.setGeometry(QRect(510, 230, 3, 160))
        self.line.setFrameShape(QFrame.VLine)
        self.line.setFrameShadow(QFrame.Sunken)
        self.label_fecha_3 = QLabel(NewBook)
        self.label_fecha_3.setObjectName(u"label_fecha_3")
        self.label_fecha_3.setGeometry(QRect(20, 210, 171, 16))
        self.label_fecha_4 = QLabel(NewBook)
        self.label_fecha_4.setObjectName(u"label_fecha_4")
        self.label_fecha_4.setGeometry(QRect(20, 240, 16, 16))
        self.label_fecha_5 = QLabel(NewBook)
        self.label_fecha_5.setObjectName(u"label_fecha_5")
        self.label_fecha_5.setGeometry(QRect(20, 270, 16, 16))
        self.label_fecha_6 = QLabel(NewBook)
        self.label_fecha_6.setObjectName(u"label_fecha_6")
        self.label_fecha_6.setGeometry(QRect(20, 300, 16, 16))
        self.label_fecha_7 = QLabel(NewBook)
        self.label_fecha_7.setObjectName(u"label_fecha_7")
        self.label_fecha_7.setGeometry(QRect(20, 330, 16, 16))
        self.label_fecha_8 = QLabel(NewBook)
        self.label_fecha_8.setObjectName(u"label_fecha_8")
        self.label_fecha_8.setGeometry(QRect(20, 360, 16, 16))
        self.inputMu1 = QLineEdit(NewBook)
        self.inputMu1.setObjectName(u"inputMu1")
        self.inputMu1.setGeometry(QRect(40, 240, 311, 20))
        font4 = QFont()
        font4.setPointSize(10)
        self.inputMu1.setFont(font4)
        self.label_fecha_9 = QLabel(NewBook)
        self.label_fecha_9.setObjectName(u"label_fecha_9")
        self.label_fecha_9.setGeometry(QRect(360, 220, 51, 20))
        self.label_fecha_10 = QLabel(NewBook)
        self.label_fecha_10.setObjectName(u"label_fecha_10")
        self.label_fecha_10.setGeometry(QRect(420, 220, 81, 16))
        self.inputCantidad1 = QLineEdit(NewBook)
        self.inputCantidad1.setObjectName(u"inputCantidad1")
        self.inputCantidad1.setGeometry(QRect(360, 240, 51, 20))
        self.inputCantidad1.setFont(font4)
        self.inputTotal1 = QLineEdit(NewBook)
        self.inputTotal1.setObjectName(u"inputTotal1")
        self.inputTotal1.setEnabled(True)
        self.inputTotal1.setGeometry(QRect(420, 240, 81, 20))
        self.inputTotal1.setFont(font4)
        self.label_fecha_11 = QLabel(NewBook)
        self.label_fecha_11.setObjectName(u"label_fecha_11")
        self.label_fecha_11.setGeometry(QRect(520, 270, 16, 16))
        self.label_fecha_12 = QLabel(NewBook)
        self.label_fecha_12.setObjectName(u"label_fecha_12")
        self.label_fecha_12.setGeometry(QRect(520, 360, 16, 16))
        self.label_fecha_13 = QLabel(NewBook)
        self.label_fecha_13.setObjectName(u"label_fecha_13")
        self.label_fecha_13.setGeometry(QRect(520, 240, 16, 16))
        self.label_fecha_14 = QLabel(NewBook)
        self.label_fecha_14.setObjectName(u"label_fecha_14")
        self.label_fecha_14.setGeometry(QRect(520, 300, 16, 16))
        self.label_fecha_15 = QLabel(NewBook)
        self.label_fecha_15.setObjectName(u"label_fecha_15")
        self.label_fecha_15.setGeometry(QRect(520, 330, 16, 16))
        self.inputMu2 = QLineEdit(NewBook)
        self.inputMu2.setObjectName(u"inputMu2")
        self.inputMu2.setGeometry(QRect(40, 270, 311, 20))
        self.inputMu2.setFont(font4)
        self.inputCantidad2 = QLineEdit(NewBook)
        self.inputCantidad2.setObjectName(u"inputCantidad2")
        self.inputCantidad2.setGeometry(QRect(360, 270, 51, 20))
        self.inputCantidad2.setFont(font4)
        self.inputTotal2 = QLineEdit(NewBook)
        self.inputTotal2.setObjectName(u"inputTotal2")
        self.inputTotal2.setEnabled(True)
        self.inputTotal2.setGeometry(QRect(420, 270, 81, 20))
        self.inputTotal2.setFont(font4)
        self.inputCantidad3 = QLineEdit(NewBook)
        self.inputCantidad3.setObjectName(u"inputCantidad3")
        self.inputCantidad3.setGeometry(QRect(360, 300, 51, 20))
        self.inputCantidad3.setFont(font4)
        self.inputMu3 = QLineEdit(NewBook)
        self.inputMu3.setObjectName(u"inputMu3")
        self.inputMu3.setGeometry(QRect(40, 300, 311, 20))
        self.inputMu3.setFont(font4)
        self.inputTotal3 = QLineEdit(NewBook)
        self.inputTotal3.setObjectName(u"inputTotal3")
        self.inputTotal3.setEnabled(True)
        self.inputTotal3.setGeometry(QRect(420, 300, 81, 20))
        self.inputTotal3.setFont(font4)
        self.inputCantidad4 = QLineEdit(NewBook)
        self.inputCantidad4.setObjectName(u"inputCantidad4")
        self.inputCantidad4.setGeometry(QRect(360, 330, 51, 20))
        self.inputCantidad4.setFont(font4)
        self.inputMu4 = QLineEdit(NewBook)
        self.inputMu4.setObjectName(u"inputMu4")
        self.inputMu4.setGeometry(QRect(40, 330, 311, 20))
        self.inputMu4.setFont(font4)
        self.inputTotal4 = QLineEdit(NewBook)
        self.inputTotal4.setObjectName(u"inputTotal4")
        self.inputTotal4.setEnabled(True)
        self.inputTotal4.setGeometry(QRect(420, 330, 81, 20))
        self.inputTotal4.setFont(font4)
        self.inputMu5 = QLineEdit(NewBook)
        self.inputMu5.setObjectName(u"inputMu5")
        self.inputMu5.setGeometry(QRect(40, 360, 311, 20))
        self.inputMu5.setFont(font4)
        self.inputTotal5 = QLineEdit(NewBook)
        self.inputTotal5.setObjectName(u"inputTotal5")
        self.inputTotal5.setEnabled(True)
        self.inputTotal5.setGeometry(QRect(420, 360, 81, 20))
        self.inputTotal5.setFont(font4)
        self.inputCantidad5 = QLineEdit(NewBook)
        self.inputCantidad5.setObjectName(u"inputCantidad5")
        self.inputCantidad5.setGeometry(QRect(360, 360, 51, 20))
        self.inputCantidad5.setFont(font4)
        self.inputCantidad7 = QLineEdit(NewBook)
        self.inputCantidad7.setObjectName(u"inputCantidad7")
        self.inputCantidad7.setGeometry(QRect(860, 270, 51, 20))
        self.inputCantidad7.setFont(font4)
        self.inputCantidad10 = QLineEdit(NewBook)
        self.inputCantidad10.setObjectName(u"inputCantidad10")
        self.inputCantidad10.setGeometry(QRect(860, 360, 51, 20))
        self.inputCantidad10.setFont(font4)
        self.inputMu7 = QLineEdit(NewBook)
        self.inputMu7.setObjectName(u"inputMu7")
        self.inputMu7.setGeometry(QRect(540, 270, 311, 20))
        self.inputMu7.setFont(font4)
        self.inputMu9 = QLineEdit(NewBook)
        self.inputMu9.setObjectName(u"inputMu9")
        self.inputMu9.setGeometry(QRect(540, 330, 311, 20))
        self.inputMu9.setFont(font4)
        self.inputTotal10 = QLineEdit(NewBook)
        self.inputTotal10.setObjectName(u"inputTotal10")
        self.inputTotal10.setGeometry(QRect(920, 360, 81, 20))
        self.inputTotal10.setFont(font4)
        self.inputTotal9 = QLineEdit(NewBook)
        self.inputTotal9.setObjectName(u"inputTotal9")
        self.inputTotal9.setGeometry(QRect(920, 330, 81, 20))
        self.inputTotal9.setFont(font4)
        self.inputTotal7 = QLineEdit(NewBook)
        self.inputTotal7.setObjectName(u"inputTotal7")
        self.inputTotal7.setGeometry(QRect(920, 270, 81, 20))
        self.inputTotal7.setFont(font4)
        self.inputCantidad9 = QLineEdit(NewBook)
        self.inputCantidad9.setObjectName(u"inputCantidad9")
        self.inputCantidad9.setGeometry(QRect(860, 330, 51, 20))
        self.inputCantidad9.setFont(font4)
        self.inputMu6 = QLineEdit(NewBook)
        self.inputMu6.setObjectName(u"inputMu6")
        self.inputMu6.setGeometry(QRect(540, 240, 311, 20))
        self.inputMu6.setFont(font4)
        self.inputMu10 = QLineEdit(NewBook)
        self.inputMu10.setObjectName(u"inputMu10")
        self.inputMu10.setGeometry(QRect(540, 360, 311, 20))
        self.inputMu10.setFont(font4)
        self.inputCantidad6 = QLineEdit(NewBook)
        self.inputCantidad6.setObjectName(u"inputCantidad6")
        self.inputCantidad6.setGeometry(QRect(860, 240, 51, 20))
        self.inputCantidad6.setFont(font4)
        self.label_fecha_16 = QLabel(NewBook)
        self.label_fecha_16.setObjectName(u"label_fecha_16")
        self.label_fecha_16.setGeometry(QRect(860, 220, 51, 20))
        self.inputCantidad8 = QLineEdit(NewBook)
        self.inputCantidad8.setObjectName(u"inputCantidad8")
        self.inputCantidad8.setGeometry(QRect(860, 300, 51, 20))
        self.inputCantidad8.setFont(font4)
        self.inputMu8 = QLineEdit(NewBook)
        self.inputMu8.setObjectName(u"inputMu8")
        self.inputMu8.setGeometry(QRect(540, 300, 311, 20))
        self.inputMu8.setFont(font4)
        self.inputTotal8 = QLineEdit(NewBook)
        self.inputTotal8.setObjectName(u"inputTotal8")
        self.inputTotal8.setGeometry(QRect(920, 300, 81, 20))
        self.inputTotal8.setFont(font4)
        self.inputTotal6 = QLineEdit(NewBook)
        self.inputTotal6.setObjectName(u"inputTotal6")
        self.inputTotal6.setGeometry(QRect(920, 240, 81, 20))
        self.inputTotal6.setFont(font4)
        self.label_fecha_17 = QLabel(NewBook)
        self.label_fecha_17.setObjectName(u"label_fecha_17")
        self.label_fecha_17.setGeometry(QRect(920, 220, 81, 16))
        self.frame = QFrame(NewBook)
        self.frame.setObjectName(u"frame")
        self.frame.setGeometry(QRect(650, 140, 351, 61))
        self.frame.setFrameShape(QFrame.StyledPanel)
        self.frame.setFrameShadow(QFrame.Raised)
        self.inputMontoTotal = QLineEdit(self.frame)
        self.inputMontoTotal.setObjectName(u"inputMontoTotal")
        self.inputMontoTotal.setEnabled(False)
        self.inputMontoTotal.setGeometry(QRect(200, 20, 151, 31))
        font5 = QFont()
        font5.setPointSize(12)
        font5.setBold(True)
        font5.setWeight(75)
        self.inputMontoTotal.setFont(font5)
        self.label_entidad_2 = QLabel(self.frame)
        self.label_entidad_2.setObjectName(u"label_entidad_2")
        self.label_entidad_2.setGeometry(QRect(200, 0, 151, 21))
        self.inputViajesRestantes = QLineEdit(self.frame)
        self.inputViajesRestantes.setObjectName(u"inputViajesRestantes")
        self.inputViajesRestantes.setEnabled(False)
        self.inputViajesRestantes.setGeometry(QRect(10, 20, 171, 31))
        self.inputViajesRestantes.setFont(font5)
        self.label_entidad_3 = QLabel(self.frame)
        self.label_entidad_3.setObjectName(u"label_entidad_3")
        self.label_entidad_3.setGeometry(QRect(10, 0, 151, 21))
        QWidget.setTabOrder(self.inputCodigo, self.inputInmueble)
        QWidget.setTabOrder(self.inputInmueble, self.inputDias)
        QWidget.setTabOrder(self.inputDias, self.inputMonto)
        QWidget.setTabOrder(self.inputMonto, self.addButton)
        QWidget.setTabOrder(self.addButton, self.cancelButton)

        self.retranslateUi(NewBook)

        self.addButton.setDefault(True)
        self.cancelButton.setDefault(True)


        QMetaObject.connectSlotsByName(NewBook)
    # setupUi

    def retranslateUi(self, NewBook):
        NewBook.setWindowTitle(QCoreApplication.translate("NewBook", u"Nuevo Registro", None))
        self.label.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p align=\"center\"><span style=\" font-size:18pt; font-weight:600; color:#ffffff;\">MODIFICAR MANTENIMIENTO CORRECTIVO TIPO 2</span></p></body></html>", None))
        self.label_autoriza.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Codigo:</span></p></body></html>", None))
        self.addButton.setText(QCoreApplication.translate("NewBook", u"MODIFICAR", None))
        self.cancelButton.setText(QCoreApplication.translate("NewBook", u"CANCELAR", None))
        self.label_aquienVisita.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Inmueble:</span></p></body></html>", None))
        self.label_area.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Departamento:</span></p></body></html>", None))
        self.label_fecha.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Fecha Inicio:</span></p></body></html>", None))
        self.label_visitante.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">D\u00edas:</span></p></body></html>", None))
        self.label_entidad.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Monto Servicio:</span></p></body></html>", None))
        self.label_dni.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Fecha Fin:</span></p></body></html>", None))
        self.label_nota_obligatoria.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt; font-weight:600; font-style:italic; color:#ff0000;\">(*) Estos campos son obligatorios</span></p></body></html>", None))
        self.ast_aquienvisita.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">*</span></p></body></html>", None))
        self.ast_dni.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">*</span></p></body></html>", None))
        self.ast_fecha.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600; color:#ff0000;\">*</span></p></body></html>", None))
        self.label_area_2.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Tipo:</span></p></body></html>", None))
        self.label_area_3.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Direcci\u00f3n:</span></p></body></html>", None))
        self.label_fecha_2.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Observaciones:</span></p></body></html>", None))
        self.label_fecha_3.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Material Utilizado:</span></p></body></html>", None))
        self.label_fecha_4.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">1.</span></p></body></html>", None))
        self.label_fecha_5.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">2.</span></p></body></html>", None))
        self.label_fecha_6.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">3.</span></p></body></html>", None))
        self.label_fecha_7.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">4.</span></p></body></html>", None))
        self.label_fecha_8.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">5.</span></p></body></html>", None))
        self.inputMu1.setText("")
        self.label_fecha_9.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Cantidad</span></p></body></html>", None))
        self.label_fecha_10.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Total</span></p></body></html>", None))
        self.inputCantidad1.setText("")
        self.label_fecha_11.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">7.</span></p></body></html>", None))
        self.label_fecha_12.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">10.</span></p></body></html>", None))
        self.label_fecha_13.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">6.</span></p></body></html>", None))
        self.label_fecha_14.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">8.</span></p></body></html>", None))
        self.label_fecha_15.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:10pt;\">9.</span></p></body></html>", None))
        self.inputMu2.setText("")
        self.inputCantidad2.setText("")
        self.inputCantidad3.setText("")
        self.inputMu3.setText("")
        self.inputCantidad4.setText("")
        self.inputMu4.setText("")
        self.inputMu5.setText("")
        self.inputCantidad5.setText("")
        self.inputCantidad7.setText("")
        self.inputCantidad10.setText("")
        self.inputMu7.setText("")
        self.inputMu9.setText("")
        self.inputCantidad9.setText("")
        self.inputMu6.setText("")
        self.inputMu10.setText("")
        self.inputCantidad6.setText("")
        self.label_fecha_16.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p align=\"center\"><span style=\" font-size:10pt;\">Cantidad</span></p></body></html>", None))
        self.inputCantidad8.setText("")
        self.inputMu8.setText("")
        self.label_fecha_17.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p align=\"center\"><span style=\" font-size:9pt;\">Total</span></p></body></html>", None))
        self.label_entidad_2.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Monto Total:</span></p></body></html>", None))
        self.label_entidad_3.setText(QCoreApplication.translate("NewBook", u"<html><head/><body><p><span style=\" font-size:12pt; font-weight:600;\">Viajes Restantes:</span></p></body></html>", None))
    # retranslateUi

